         MACRO
&LABEL   BIN2STR &SOURCE,&TARGET
         AIF   ('&SOURCE'(1,1) NE '(').REGNOT
&LABEL   LR    R1,&SOURCE(1)
         AGO   .STRALL
.REGNOT  ANOP
&LABEL   L    R1,&SOURCE
.STRALL  ANOP
         CVD  R1,STRPACK                CONVERT SOURCE NUMBER
         UNPK &TARGET,STRPACK           UNPACK NUMBER
         OI   &TARGET+L'&TARGET-1,X'F0' CORRECT SIGN (LAST BYTE)
         MEND
