         MACRO
&LABEL   BIN2CHR &TARGET,&SOURCE
&LABEL   BIN2PAK STRPACK,&SOURCE
         UNPK  &TARGET,STRPACK           UNPACK NUMBER
         OI    &TARGET+L'&TARGET-1,X'F0' CORRECT SIGN (LAST BYTE)
         MEND
