         MACRO
&LABEL   BIN2PAK &TARGET,&SOURCE
         AIF   ('&SOURCE'(1,1) NE '(').REGNOT
&LABEL   CVD   &SOURCE(1),STRPACK        CONVERT SOURCE NUMBER
         AGO   .STRALL
.REGNOT  ANOP
&LABEL   L     R1,&SOURCE
         CVD   R1,&TARGET                CONVERT SOURCE NUMBER
.STRALL  ANOP
         MEND
