* THE CALL VERSION MUST BE CHANGED IF THIS TABLE CHANGES;
* UNLESS NEW STUFF IS ADDED TO THE END TO MAINTAIN COMPATIBILITY
CALLVERS DC   CL4'V1M0'
CALLTAB  DS   0F
* THE CCALL MACRO IS IN WDPSC.MACLIB(CCALL)
         CCALL    @FLSTAT
         CCALL    ABORT
         CCALL    ABS
         CCALL    ACOS
         CCALL    ASCTIME
         CCALL    ASIN
         CCALL    ATAN
         CCALL    ATAN2
         CCALL    ATOF
         CCALL    ATOI
         CCALL    ATOL
         CCALL    CALLOC
         CCALL    CEIL
         CCALL    CLEARERR
         CCALL    CLOCK
         CCALL    COS
         CCALL    COSH
         CCALL    CTIME
         CCALL    DIFFTIME
         CCALL    ERF
         CCALL    ERFC
         CCALL    EXIT
         CCALL    EXP
         CCALL    FABS
         CCALL    FCLOSE
         CCALL    FEOF
         CCALL    FERROR
         CCALL    FFLUSH
         CCALL    FGETC
         CCALL    FGETS
         CCALL    FLOOR
         CCALL    FMOD
         CCALL    FOPEN
         CCALL    FPRINTF
         CCALL    FPUTC
         CCALL    FPUTS
         CCALL    FREAD
         CCALL    FREE
         CCALL    FREOPEN
         CCALL    FREXP
         CCALL    FSCANF
         CCALL    FSEEK
         CCALL    FTELL
         CCALL    FWRITE
         CCALL    GAMMA
         CCALL    GETC
         CCALL    GETCHAR
         CCALL    GETENV
         CCALL    GETS
         CCALL    GMTIME
         CCALL    HYPOT
         CCALL    ISALNUM
         CCALL    ISALPHA
         CCALL    ISCNTRL
         CCALL    ISDIGIT
         CCALL    ISGRAPH
         CCALL    ISLOWER
         CCALL    ISPRINT
         CCALL    ISPUNCT
         CCALL    ISSPACE
         CCALL    ISUPPER
         CCALL    ISXDIGIT
         CCALL    JN
         CCALL    J0
         CCALL    J1
         CCALL    KILL
         CCALL    LDEXP
         CCALL    LOCALTIM
         CCALL    LOG
         CCALL    LOG10
         CCALL    MALLOC
         CCALL    MEMCHR
         CCALL    MEMCMP
         CCALL    MEMCPY
         CCALL    MEMSET
         CCALL    MODF
         CCALL    ONEXIT
         CCALL    PERROR
         CCALL    POW
         CCALL    PRINTF
         CCALL    PUTC
         CCALL    PUTCHAR
         CCALL    PUTS
         CCALL    RAND
         CCALL    REALLOC
         CCALL    REMOVE
         CCALL    RENAME
         CCALL    REWIND
         CCALL    SCANF
         CCALL    SETBUF
         CCALL    SETVBUF
         CCALL    SIGNAL
         CCALL    SIN
         CCALL    SINH
         CCALL    SPRINTF
         CCALL    SQRT
         CCALL    SRAND
         CCALL    SSCANF
         CCALL    STRCAT
         CCALL    STRCHR
         CCALL    STRCMP
         CCALL    STRCPY
         CCALL    STRCSPN
         CCALL    STRLEN
         CCALL    STRNCAT
         CCALL    STRNCMP
         CCALL    STRNCPY
         CCALL    STRPBRK
         CCALL    STRRCHR
         CCALL    STRSPN
         CCALL    STRTOD
         CCALL    STRTOK
         CCALL    STRTOL
         CCALL    SYSTEM
         CCALL    TAN
         CCALL    TANH
         CCALL    TIME
         CCALL    TMPFILE
         CCALL    TMPNAM
         CCALL    TOLOWER
         CCALL    TOUPPER
         CCALL    UNGETC
         CCALL    VFPRINTF
         CCALL    VPRINTF
         CCALL    VSPRINTF
         CCALL    YN
         CCALL    Y0
         CCALL    Y1
