       MACRO
&NAME  SASCOMU
.*  THIS MACRO DEFINES A USER WORK AREA WITHIN THE SAS COMMUNICATIONS
.*  BLOCK.
WHEADER DS  CL1
*   VALUE OF X'DC' INDICATES PREVIOUS PASSAGE THROUGH G78SEPH1
.*
        MEND
